version: 2
updates:
  # Enable version updates for yarn
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for every friday
    schedule:
      interval: 'weekly'
      day: 'friday'
    # Custom commit messages
    commit-message:
      prefix: 'bot: :alien:'
    reviewers:
      - 'chxru'
