version: '3.9'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  mongo:
    image: mongo:6.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - db:/data/db

volumes:
  db:
