name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      - run: npx nx workspace-lint

      - run: npx nx format:check

      - run: npx nx affected --target=lint --parallel=3

      - run: npx nx affected --target=test --parallel=3 --ci --code-coverage
